version: '3.9'

services:
  peluqueria:
    image: postgres:16.2
    container_name: peluqueria-db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=peluqueria
    volumes:
      - ./postgres:/var/lib/postgresql/data